<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modulo;

class ModuloSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $modulos = [
            // ========================
            // CORE DEL SISTEMA
            // ========================
            [
                'nombre' => 'Dashboard',
                'slug' => 'dashboard',
                'descripcion' => 'Panel principal con métricas y accesos rápidos.',
                'icono' => 'layout-dashboard',
                'ruta' => '/admin/dashboard',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 1,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Usuarios y Roles',
                'slug' => 'usuarios-roles',
                'descripcion' => 'Gestión de usuarios, roles y permisos.',
                'icono' => 'users',
                'ruta' => '/usuarios',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 2,
                'configuracion_default' => [],
                'es_admin' => false,
            ],
            [
                'nombre' => 'Copropiedades',
                'slug' => 'copropiedades',
                'descripcion' => 'Gestión de copropiedades y unidades.',
                'icono' => 'building',
                'ruta' => '/copropiedades',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 3,
                'configuracion_default' => [],
                'es_admin' => false,
            ],
            [
                'nombre' => 'Configuración General',
                'slug' => 'configuracion-general',
                'descripcion' => 'Configuraciones globales del sistema.',
                'icono' => 'settings',
                'ruta' => '/configuracion',
                'activo' => true,
                'requiere_configuracion' => true,
                'orden' => 4,
                'configuracion_default' => [
                    'permitir_reservas_con_mora' => false,
                    'permitir_visitantes_con_mora' => true,
                    'habilitar_notificaciones_push' => true,
                ],
                'es_admin' => false,
            ],

            // ========================
            // GESTIÓN ADMINISTRATIVA
            // ========================
            [
                'nombre' => 'Cartera y Pagos',
                'slug' => 'cartera',
                'descripcion' => 'Gestión de cartera, pagos y estados de cuenta.',
                'icono' => 'wallet',
                'ruta' => '/admin/cartera',
                'activo' => true,
                'requiere_configuracion' => true,
                'orden' => 10,
                'configuracion_default' => [
                    'permitir_pagos_parciales' => true,
                    'aplicar_intereses_por_mora' => true,
                    'habilitar_pagos_en_linea' => true,
                ],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Reservas de Zonas Comunes',
                'slug' => 'reservas-zonas-comunes',
                'descripcion' => 'Gestión de reservas de áreas comunes.',
                'icono' => 'calendar',
                'ruta' => '/reservas',
                'activo' => true,
                'requiere_configuracion' => true,
                'orden' => 11,
                'configuracion_default' => [
                    'requerir_aprobacion_reservas' => false,
                    'limitar_reservas_por_mes' => 4,
                ],
                'es_admin' => false,
            ],
            [
                'nombre' => 'Comunicados',
                'slug' => 'comunicados',
                'descripcion' => 'Publicación de comunicados a residentes.',
                'icono' => 'megaphone',
                'ruta' => '/admin/comunicados',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 12,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Correspondencia',
                'slug' => 'correspondencia',
                'descripcion' => 'Gestión de correspondencia recibida.',
                'icono' => 'mail',
                'ruta' => '/admin/correspondencias',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 13,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Visitas',
                'slug' => 'visitas',
                'descripcion' => 'Gestión de visitantes y accesos.',
                'icono' => 'user-check',
                'ruta' => '/admin/visitas',
                'activo' => true,
                'requiere_configuracion' => true,
                'orden' => 14,
                'configuracion_default' => [
                    'habilitar_acceso_qr' => true,
                    'requerir_aprobacion_residente_visitas' => true,
                ],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Autorizaciones',
                'slug' => 'autorizaciones',
                'descripcion' => 'Gestión de autorizaciones para personal y proveedores.',
                'icono' => 'id-card',
                'ruta' => '/admin/autorizaciones',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 15,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Llamados de Atención',
                'slug' => 'llamados-atencion',
                'descripcion' => 'Gestión de llamados de atención y casos de convivencia.',
                'icono' => 'exclamation-triangle',
                'ruta' => '/admin/llamados-atencion',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 16,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'PQRS',
                'slug' => 'pqrs',
                'descripcion' => 'Gestión de peticiones, quejas, reclamos y sugerencias.',
                'icono' => 'message-square',
                'ruta' => '/admin/pqrs',
                'activo' => true,
                'requiere_configuracion' => true,
                'orden' => 17,
                'configuracion_default' => [
                    'permitir_pqrs_anonimas' => false,
                    'habilitar_sla_pqrs' => true,
                ],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Sorteos Parqueaderos',
                'slug' => 'sorteos-parqueadero',
                'descripcion' => 'Gestión de sorteos de parqueaderos.',
                'icono' => 'car',
                'ruta' => '/admin/sorteos-parqueadero',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 18,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Manual de Convivencia',
                'slug' => 'manual-convivencia',
                'descripcion' => 'Gestión del manual de convivencia de la copropiedad.',
                'icono' => 'book',
                'ruta' => '/admin/manual-convivencia',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 19,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Unidades',
                'slug' => 'unidades',
                'descripcion' => 'Gestión de unidades de la copropiedad.',
                'icono' => 'home',
                'ruta' => '/admin/unidades',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 20,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Residentes',
                'slug' => 'residentes',
                'descripcion' => 'Gestión de residentes de la copropiedad.',
                'icono' => 'users',
                'ruta' => '/admin/residentes',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 21,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Depositos',
                'slug' => 'depositos',
                'descripcion' => 'Gestión de depósitos de la copropiedad.',
                'icono' => 'package',
                'ruta' => '/admin/depositos',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 22,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Cuotas Admnistracion',
                'slug' => 'cuotas-administracion',
                'descripcion' => 'Gestión de cuotas de administración.',
                'icono' => 'file-text',
                'ruta' => '/admin/cuotas-administracion',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 23,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Cartera',
                'slug' => 'cartera',
                'descripcion' => 'Gestión de cartera de la copropiedad.',
                'icono' => 'wallet',
                'ruta' => '/admin/cartera',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 24,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Cuentas Cobro',
                'slug' => 'cuentas-cobro',
                'descripcion' => 'Gestión de cuentas de cobro.',
                'icono' => 'receipt',
                'ruta' => '/admin/cuentas-cobro',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 25,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Recaudo',
                'slug' => 'recaudo',
                'descripcion' => 'Gestión de recaudos.',
                'icono' => 'dollar-sign',
                'ruta' => '/admin/recaudos',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 26,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Acuerdos Pagos',
                'slug' => 'acuerdos-pagos',
                'descripcion' => 'Gestión de acuerdos de pago.',
                'icono' => 'handshake',
                'ruta' => '/admin/acuerdos-pagos',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 27,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Reservas',
                'slug' => 'reservas',
                'descripcion' => 'Gestión de reservas de zonas comunes.',
                'icono' => 'calendar',
                'ruta' => '/admin/reservas',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 28,
                'configuracion_default' => [],
                'es_admin' => true,
            ],

            // ========================
            // COMUNIDAD
            // ========================
            [
                'nombre' => 'Mascotas',
                'slug' => 'mascotas',
                'descripcion' => 'Registro y control de mascotas.',
                'icono' => 'paw-print',
                'ruta' => '/admin/mascotas',
                'activo' => true,
                'requiere_configuracion' => true,
                'orden' => 30,
                'configuracion_default' => [
                    'limitar_mascotas_por_unidad' => 2,
                ],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Parqueaderos',
                'slug' => 'parqueaderos',
                'descripcion' => 'Gestión de parqueaderos.',
                'icono' => 'car',
                'ruta' => '/admin/parqueaderos',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 31,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Zonas Comunes',
                'slug' => 'zonas-comunes',
                'descripcion' => 'Gestión de zonas comunes y áreas sociales.',
                'icono' => 'swimming-pool',
                'ruta' => '/admin/zonas-sociales',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 32,
                'configuracion_default' => [],
                'es_admin' => true,
            ],

            // ========================
            // CONTROL Y SEGURIDAD
            // ========================
            [
                'nombre' => 'Reportes',
                'slug' => 'reportes',
                'descripcion' => 'Reportes y estadísticas del sistema.',
                'icono' => 'file-text',
                'ruta' => '/reportes',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 50,
                'configuracion_default' => [],
                'es_admin' => false,
            ],
            [
                'nombre' => 'Auditoría',
                'slug' => 'auditoria',
                'descripcion' => 'Registro de acciones del sistema.',
                'icono' => 'activity',
                'ruta' => '/auditoria',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 51,
                'configuracion_default' => [],
                'es_admin' => false,
            ],
            [
                'nombre' => 'Notificaciones',
                'slug' => 'notificaciones',
                'descripcion' => 'Gestión de notificaciones del sistema.',
                'icono' => 'bell',
                'ruta' => '/notificaciones',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 52,
                'configuracion_default' => [],
                'es_admin' => false,
            ],
            [
                'nombre' => 'Usuarios Admin',
                'slug' => 'usuarios-admin',
                'descripcion' => 'Gestión de usuarios administrados por el administrador de la propiedad.',
                'icono' => 'user-cog',
                'ruta' => '/admin/usuarios-admin',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 29,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Encuestas y Votaciones',
                'slug' => 'encuestas-votaciones',
                'descripcion' => 'Gestión de encuestas y votaciones para la copropiedad.',
                'icono' => 'clipboard-list',
                'ruta' => '/admin/encuestas-votaciones',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 33,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            [
                'nombre' => 'Cartelera de Licitaciones',
                'slug' => 'cartelera-licitaciones',
                'descripcion' => 'Gestión de licitaciones públicas y ofertas de proveedores.',
                'icono' => 'file-text',
                'ruta' => '/admin/cartelera-licitaciones',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 34,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
            // ========================
            // CONSEJO DE ADMINISTRACIÓN
            // ========================
            [
                'nombre' => 'Consejo Integrantes',
                'slug' => 'consejo-integrantes',
                'descripcion' => 'Gestión de integrantes del Consejo de Administración.',
                'icono' => 'users',
                'ruta' => '/admin/consejo-integrantes',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 35,
                'configuracion_default' => [],
                'es_admin' => true,
                'es_consejo' => true,
            ],
            [
                'nombre' => 'Consejo Reuniones',
                'slug' => 'consejo-reuniones',
                'descripcion' => 'Gestión de reuniones del Consejo de Administración.',
                'icono' => 'calendar',
                'ruta' => '/admin/consejo-reuniones',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 36,
                'configuracion_default' => [],
                'es_admin' => true,
                'es_consejo' => true,
            ],
            [
                'nombre' => 'Actas de Reuniones',
                'slug' => 'consejo-actas',
                'descripcion' => 'Gestión de actas de las reuniones del Consejo.',
                'icono' => 'file-text',
                'ruta' => '/admin/consejo-actas',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 37,
                'configuracion_default' => [],
                'es_admin' => true,
                'es_consejo' => true,
            ],
            [
                'nombre' => 'Decisiones del Consejo',
                'slug' => 'consejo-decisiones',
                'descripcion' => 'Gestión de decisiones tomadas en el Consejo.',
                'icono' => 'check-circle',
                'ruta' => '/admin/consejo-decisiones',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 38,
                'configuracion_default' => [],
                'es_admin' => true,
                'es_consejo' => true,
            ],
            [
                'nombre' => 'Tareas y Seguimiento',
                'slug' => 'consejo-tareas',
                'descripcion' => 'Gestión de tareas y seguimiento del Consejo.',
                'icono' => 'clipboard-check',
                'ruta' => '/admin/consejo-tareas',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 39,
                'configuracion_default' => [],
                'es_admin' => true,
                'es_consejo' => true,
            ],
            [
                'nombre' => 'Comunicaciones del Consejo',
                'slug' => 'consejo-comunicaciones',
                'descripcion' => 'Gestión de comunicaciones oficiales del Consejo.',
                'icono' => 'mail',
                'ruta' => '/admin/consejo-comunicaciones',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 40,
                'configuracion_default' => [],
                'es_admin' => true,
                'es_consejo' => true,
            ],
            // ========================
            // ASAMBLEAS
            // ========================
            [
                'nombre' => 'Asambleas',
                'slug' => 'asambleas',
                'descripcion' => 'Gestión de asambleas de copropietarios.',
                'icono' => 'users',
                'ruta' => '/admin/asambleas',
                'activo' => true,
                'requiere_configuracion' => false,
                'orden' => 41,
                'configuracion_default' => [],
                'es_admin' => true,
            ],
        ];

        foreach ($modulos as $modulo) {
            Modulo::updateOrCreate(
                ['slug' => $modulo['slug']],
                $modulo
            );
        }

        $this->command->info('Módulos creados exitosamente: ' . count($modulos));
    }
}
